pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["abc_butce.htm","Abc_Butce","Abc_Butce",""],
["abc_finans.htm","Abc_Finans","Abc_Finans",""],
["abc_genel.htm","Abc_Genel","Abc_Genel",""],
["abc_hesap.htm","Abc_Hesap","Abc_Hesap",""],
["abc_menu.htm","Abc_Menu","Abc_Menu",""],
["abc_rapor.htm","Abc_Rapor","Abc_Rapor",""],
["abc_satinalma.htm","Abc_Satinalma","Abc_Satinalma",""],
["abc_sistem.htm","Abc_Sistem","Abc_Sistem",""],
["abc_stok.htm","Abc_Stok","Abc_Stok",""]];
