pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["abc_butce-tahmin.htm","Bütçe &#62; Tahmini Bütçe","Tahmini Bütçe",""],
["abc_butce.htm","Bütçe","Bütçe",""],
["abc_finans-als-fat.htm","Finans &#62; Alış Fatura","Alış Fatura",""],
["abc_finans-mahsup.htm","Finans &#62; Mahsup","Mahsup",""],
["abc_finans-odeme.htm","Finans &#62; Ödeme","Ödeme",""],
["abc_finans-oto.htm","Finans &#62; Otomatik Fiş Oluştur","Otomatik Fiş Oluştur",""],
["abc_finans-sat-fat.htm","Finans &#62; Satış Fatura","Satış Fatura",""],
["abc_finans-tahsil.htm","Finans &#62; Tahsilat","Tahsilat",""],
["abc_finans.htm","Finans","Finans",""],
["abc_genel.htm","Program Hakkında","Yemek Firmaları İçin Takip Programı",""],
["abc_hesap-frm.htm","Hesap Tanım &#62; Firma Hesapları","Firma Hesapları",""],
["abc_hesap-gel.htm","Hesap Tanım &#62; Gelir Hizmet Hesapları","Gelir Hizmet Hesapları",""],
["abc_hesap-gid.htm","Hesap Tanım &#62; Gider Hizmet Hesapları","Gider Hizmet Hesapları",""],
["abc_hesap-mus.htm","Hesap Tanım &#62; Müşteri Hesapları","Müşteri Hesapları",""],
["abc_hesap-nak.htm","Hesap Tanım &#62; Nakit Hesapları","Nakit Hesapları",""],
["abc_hesap-per.htm","Hesap Tanım &#62; Personel Hesapları","Personel Hesapları",""],
["abc_hesap-tip.htm","Hesap Tanım &#62; Hesap Tipleri","Hesap Tipleri",""],
["abc_hesap.htm","Hesap Tanım","Hesap Tanım",""],
["abc_menu-menu.htm","Menü Tanım &#62; Menu Tanımları","Menu Tanımları",""],
["abc_menu-mlz.htm","Menü Tanım &#62; Malzeme Tanımları","Malzeme Tanımları",""],
["abc_menu-ymk.htm","Menü Tanım &#62; Yemek/Ürün Tanımları","Yemek/Ürün Tanımları",""],
["abc_menu.htm","Menü Tanım","Menü Tanım",""],
["abc_rapor-but-pivot.htm","Raporlama &#62; Bütçe Pivot","Bütçe Pivot",""],
["abc_rapor-fin-pivot.htm","Raporlama &#62; Finans Pivot","Finans Pivot",""],
["abc_rapor-hsp-dur-sor.htm","Raporlama &#62; Hesap Durum Sorgula","Hesap Durum Sorgula",""],
["abc_rapor-hsp-har-sor.htm","Raporlama &#62; Hesap Hareket Sorgula","Hesap Hareket Sorgula",""],
["abc_rapor-stk-dur-sor.htm","Raporlama &#62; Stok Durum Sorgula","Stok Durum Sorgula",""],
["abc_rapor-stk-har-sor.htm","Raporlama &#62; Stok Hareket Sorgula","Stok Hareket Sorgula",""],
["abc_rapor-stk-pivot.htm","Raporlama &#62; Stok Pivot","Stok Pivot",""],
["abc_rapor-yazici.htm","Raporlama &#62; Yazıcı Raporları","Yazıcı Raporları",""],
["abc_rapor.htm","Raporlama","Raporlama",""],
["abc_satinalma-ist-tal.htm","Satınalma &#62; Satınalma İstek Talebi","Satınalma İstek Talebi",""],
["abc_satinalma-onay.htm","Satınalma &#62; Satınalma Onayı","Satınalma Onayı",""],
["abc_satinalma-tek-gir.htm","Satınalma &#62; Satınalma Teklif Girişi","Satınalma Teklif Girişi",""],
["abc_satinalma.htm","Satınalma","Satınalma",""],
["abc_sistem-fin-hrk.htm","Sistem Yönetim &#62; Finans Hareket Tanımları","Finans Hareket Tanımları",""],
["abc_sistem-kod.htm","Sistem Yönetim &#62; Seçim Kod Tanımları","Seçim Kod Tanımları",""],
["abc_sistem-kul-grp.htm","Sistem Yönetim &#62; Kullanıcı Gruplari","Kullanıcı Gruplari",""],
["abc_sistem-kul-tan.htm","Sistem Yönetim &#62; Kullanıcı Tanımı","Kullanıcı Tanımı",""],
["abc_sistem-org-dep.htm","Sistem Yönetim &#62; Organizasyon-Departman","Organizasyon-Departman",""],
["abc_sistem-org-don.htm","Sistem Yönetim &#62; Organizasyon-Dönem","Organizasyon-Dönem",""],
["abc_sistem-org-hol.htm","Sistem Yönetim &#62; Organizasyon-Holding","Organizasyon-Holding",""],
["abc_sistem-prj.htm","Sistem Yönetim &#62; Proje Menu Bilgileri","Proje Menu Bilgileri",""],
["abc_sistem-prm.htm","Sistem Yönetim &#62; Parametre Tanımları","Parametre Tanımları",""],
["abc_sistem-stk-brm.htm","Sistem Yönetim &#62; Stok Birim Tanımları","Stok Birim Tanımları",""],
["abc_sistem-stk-hrk.htm","Sistem Yönetim &#62; Stok Hareket Tanımları","Stok Hareket Tanımları",""],
["abc_sistem.htm","Sistem Yönetim","Sistem Yönetim",""],
["abc_stok-als-irs.htm","Stok &#62; Alış İrsaliye","Alış İrsaliye",""],
["abc_stok-depo.htm","Stok &#62; Depo İşlemleri","Depo İşlemleri",""],
["abc_stok-ist-ona.htm","Stok &#62; Stok İstek Onayı","Stok İstek Onayı",""],
["abc_stok-ist-tal.htm","Stok &#62; Stok İstek Talebi","Stok İstek Talebi",""],
["abc_stok-sat-irs.htm","Stok &#62; Satış İrsaliye","Satış İrsaliye",""],
["abc_stok.htm","Stok","Stok",""]];
